spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ypb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: admin123
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 15
      max-wait: 30000
      validation-query: SELECT 1
      validation-query-timeout: 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true

  #Redis配置
  redis:
    host: 192.168.7.242
    port: 6379
    database: 0
    jedis:
      pool:
        #最大连接数（负值表示没有限制）
        max-active: 100
        #最大空闲链接
        max-idle: 10
        #最小空闲链接
        min-idle: 5
        #最大阻塞时间 负值表示不限制
        max-wait: -1ms

# canal相关配置
canal:
  host: 192.168.174.128
  port: 2100
  destination: example
  username:
  password:
  subscribe: book\..*
  batchSize: 1000
  zkServers: 192.168.174.128:2181,192.168.174.128:2182,192.168.174.128:2183
# subscribe 过滤规则
# 1）  所有：.*   or  .*\..*
# 2）  "test"库下所有表： test\..*
# 3）  "test"下的以"sys"打头的表：test\.sys.*
# 4）  "test"下的具体一张表：test.blog   blog表
# 5）  多个规则组合使用：test\..*,test.sys_user,test.sys_role (逗号分隔)

mybatis:
  config-location: classpath:mybatis-config.xml
